<?xml version="1.0"?>

<!-- included by, and macro expanded in, diffbot_urdf.xacro -->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

    <xacro:property name="base_width" value="0.1"/>
    <xacro:property name="base_height" value="0.05"/>
    <xacro:property name="z_offset" value="-${base_height/2}"/>

    <link name="${prefix}base_link"/>

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${base_width/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <link name="${prefix}left_wheel"/>

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${base_width/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <link name="${prefix}right_wheel"/>

  </xacro:macro>

</robot>
