controller_manager:
  ros__parameters:
    update_rate: 10
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# diff_drive_controller user doc:
# https://control.ros.org/jazzy/doc/ros2_controllers/diff_drive_controller/doc/userdoc.html

diffbot_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # Measured
    wheel_separation: 0.137
    wheel_radius: 0.050

    # Default for this is 50. Perhaps 10 is too low, especially since
    # velocity_rolling_window_size defaults to 10. Must be double!
    publish_rate: 10.0

    odom_frame_id: odom # Not the topic - the tf frame ID
    base_frame_id: base_link

    # It would be nice to figure out what these might affect. These values are
    # suggested as starting points in the diff_drive_controller user doc.
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    linear.x:
      max_velocity: 0.5         # m/sec
      max_acceleration: 0.5     # m/sec^2
      max_jerk: .NAN

    angular.z:
      max_velocity: 3.1416      # rad/sec
      max_acceleration: 3.1416  # rad/sec^2
      max_jerk: .NAN
